### ISSUE TITLE
[WIP] Refactoring

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik-php-tracker#1]
Hello,

since this is a BC break anyway i would like to use it as a refactoring point.
- namespacing
- cleanup / splitting
- phpunit testing
- ...

I started here https://github.com/ThaDafinser/piwik-tracker

**Comment by JulienMoumne** [comment]
How about not having to maintain a PHP version anymore ? https://github.com/piwik/piwik-dotnet-tracker/issues/12

**Comment by mattab** [comment]
We're now managing the project with composer and we kept full backward compatibility. If anyone wants to help further improve the project please open new pull request / issue :+1: You'll be very welcome :smile:
