### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by JohnMaguire** [piwik/piwik-php-tracker#16]
Hi there,

I'm working on solving piwik/piwik#6870, and to use composer well, this package would need to be versioned. The latest version packagist knows about is 1.0.0 (as defined by the Releases page).

If you could create a new release, we can make sure that the switch to managing PiwikTracker.php through composer doesn't downgrade the version of PiwikTracker.

Thanks!

**Comment by tsteur** [comment]
I just tagged a new release 1.0.1 if that's alright?
