### ISSUE TITLE
Do not ignore Errors: throw exceptions

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik-php-tracker#3]
I'm opening this issue to keep track of it and have it fixed in the future.

If the HTTP call to the Tracker API returns a HTTP error (500, …) it will be ignored.

See https://github.com/piwik/piwik-php-tracker/blob/master/PiwikTracker.php#L1352

It might be better to throw exceptions, but I have no idea what would be the BC break.

**Comment by mattab** [comment]
We'll keep it simple and not do error handling in this class for now. Maybe we change our mind in the future... If error handling is needed, one could fetch the URLs using the `getUrl*` methods and then manually send http request and deal with errors.
